apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    azure:
      secretStorage:
        keyVaultName: champion-foxhound
      storage:
        storageAccountName: jxchampionfoxhound
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    environmentGitOwner: bluegreendeployment
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider:  aks
    registry: championfoxhound.azurecr.io
  environments:
  - key: dev
    owner: bluegreendeployment
    repository: Cluster
  - key: staging
  - key: production
  ingress:
    domain: 20.76.182.121.nip.io
    externalDNS: true
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: FalkWinkler
  repository: nexus
  secretStorage: azurekeyvault
  storage:
  - name: logs
    url: azblob://logs
  vault: {}
  webhook: lighthouse
