# Source: jenkins-resources/templates/maven-settings-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-maven-settings
  namespace: myjenkins
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: azureKeyVault
  keyVaultName: champion-foxhound
  data:
    - name: settings.xml
      key: jx-maven-settings
      property: settingsXml
    - name: settings-security.xml
      key: jx-maven-settings
      property: securityXml
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'jenkins-resources'
    type: Opaque
