# Source: jenkins-resources/templates/tekton-container-registry-auth-secret.yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: tekton-container-registry-auth
  namespace: myjenkins
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  backendType: azureKeyVault
  keyVaultName: champion-foxhound
  data:
    - name: .dockerconfigjson
      key: tekton-container-registry-auth
  template:
    metadata:
      annotations:
        meta.helm.sh/release-name: 'jenkins-resources'
    type: kubernetes.io/dockerconfigjson
